---
title: Reserve an Enso today
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: Keep the heartbeat of someone you love... forever.
image: http://shareenso.com/self-hug.jpg
email: support@shareenso.com
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
plugins:
- jekyll/imgix
- jekyll-feed
- jekyll-assets
- jekyll-seo-tag
- octopress-minify-html
assets:
  assets:
  - application.css
  autoprefixer:
    browsers:
    - last 2 versions
    - IE > 9
  autowrite: true
  prefix: "/assets"
  digest: true
  sources:
  - _assets/css
  - _assets/js
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
