---
title: Reserve an Enso today
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: Keep the heartbeat of someone you love... forever.
image: http://shareenso.com/self-hug.jpg
email: support@shareenso.com
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
relative_links:
  enabled:     true
  collections: false
sass:
  sass_dir: css
  style: compressed
gems:
  - jekyll-relative-links
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
