---
title: Order an Enso today
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: Keep the heartbeat of someone you love... forever.
image: http://shareenso.com/self-hug.jpg
email: support@shareenso.com
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
relative_links:
  enabled: true
  collections: false
sass:
  sass_dir: css
  style: compressed
plugins:
- jekyll-relative-links
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
quotes:
- entry:
  - I am planning to give one to my love and keep one for myself... At first, I just
    wanted to get one for him so that when he’s away, he’d have a physical representation
    of knowing he had my heart with him.
  - When I saw that you could each hold the enso and feel each other’s heartbeat live,
    in the moment, I knew I had to have two.
  cite: Anima
- entry:
  - I love the idea of Enso, a palpable way to connect with someone who you cannot
    be with at the moment. I will be capturing the heart beats of my family members…
  - I am going to be also using to capture the heartbeat of a very close friend that
    I often miss and will also be gifting it to her.
  cite: J
- entry:
  - I travel a great deal for my company...so the Enso was actually for my wife and
    two year-old son rather than for me. The few times I have been able to come home,
    it's usually late at night from whatever flight I've just come off of and I do
    my best not to wake my wife and son - but when I finally crawl into bed before
    getting back up for the next flight in the morning, I usually find the Enso on
    the pillow just near my wife's hand.  Thanks for helping us stay connected, one
    heartbeat at a time. 
  cite: Anonymous
- entry:
  - My Mom is a Holocaust survivor and is in stages of dementia. My daughter is having
    a baby in 2 weeks and I am planning to give the Enso as a gift to my daughter,
    with my Moms heartbeat ❤
  cite: H.P.
- entry:
  - My first thought is to save my father's (Papa) heartbeat. I don’t see him often;
    he’s 74 years old as healthy-as-a-horse and a tough-as-nails cowboy. He’s not
    going anywhere anytime soon but I’d hate to know I could have captured the feeling
    of being with him when I could have and then didn’t... Papa’s a big softy and
    I know it will be as meaningful for him as it is for me.
  cite: K.T.
- entry:
  - 'I love [my Enso]. I got one for my dad for Christmas and he likes it too. He
    works in construction and he shows it off to the other guys he works with in meetings.
    I think he uses it for his anxiety. I like to use it to help me meditate and fall
    asleep. I love it and would recommend it to anyone! '
  cite: Taylor  Madison
- entry:
  - We have had some tough losses in the family in recent years. I thought this would
    be a tremendous way to capture and hold a piece of cherished loved ones. Eternally.
    A visceral reminder and means of staying connected wherever, whenever, and for
    whatever reason one desires.
  cite: Anonymous
- entry:
  - I am planning to use [Enso] to capture the heartbeats of the people that capture
    my heart. They will be a collection of the people that have played important roles
    in my life. I will leave mine on there for fun and then leave it for my daughter
    to carry on on the legacy and her own heartbeats.
  cite: Wendi Michelle
- entry:
  - I will be giving the Enso to my wife for Christmas. 2 years ago, my wife gave
    birth to our son, she finds it very hard leaving him everyday for work...My plan
    is to have our son hold it, then wrap it up, Christmas morning she will get the
    gift of always having him with her.
  cite: Anonymous
- entry:
  - It's a present for my husband who travels a lot. I would like to have our son     's
    heartbeat always with him ❤
  cite: Anonymous
